[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dao_vote = "6f5HD6HfhDScH56N59mcGeDa44vCwdQF65JyZS668pJf"
notebox = "2gkh4PKHmENrdnjNmb515KVbvpdWGsvbDtQ4qzC2FqrV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/dao_vote", "programs/notebox"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
